### ISSUE TITLE
Update this library to Darts null safety

### ISSUE THREAD

**Issue by ueman** [alex-melnyk/flutter_advanced_switch#1]
The next stable release of Flutter is using most probably Darts new null safety feature.
Thus this library should be migrated.

Please see the following links for further information:
https://dart.dev/null-safety/migration-guide
https://medium.com/flutter/announcing-dart-null-safety-beta-4491da22077a

**Comment by jlnrrg** [comment]
With Flutter 2.0 released and null safety now in the stable channel, I second this.

**Comment by alex-melnyk** [comment]
Dear @ueman and @jlnrrg 
I'll appreciate it if you guys help me with that using the PR, in any other cases you will wait till I have time for that.
