### ISSUE TITLE
AnimationController.reverse() called after AnimationController.dispose()

### ISSUE THREAD

**Issue by Alijaaan** [alex-melnyk/flutter_advanced_switch#12]
Hi Alex,

I tried to add some switch items in my drawer.
the first time on opening drawer everything is Ok.
But when I close the drawer and re open it, I receive error:

======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for AdvancedSwitchController:
AnimationController.reverse() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
'package:flutter/src/animation/animation_controller.dart':
Failed assertion: line 488 pos 7: '_ticker != null'

Thanks in Advance

**Comment by alex-melnyk** [comment]
@Alijaaan please check the 3.0.0 version
