### ISSUE TITLE
Widget gets shown when not supposed to

### ISSUE THREAD

**Issue by itamarsch** [alex-melnyk/flutter_advanced_switch#18]
https://user-images.githubusercontent.com/71348842/156032376-d1dbe2fb-3b26-4439-8f38-ce5aa521ec15.mp4

![image](https://user-images.githubusercontent.com/71348842/156032391-85a69f56-42d9-4fd6-b67a-79e17bf49f7e.png)
 
This issue from what I gather only happens when I run the app on ios

**Comment by alex-melnyk** [comment]
Please check v3.0.1
