### ISSUE TITLE
onchanged function

### ISSUE THREAD

**Issue by Yogesh-333** [alex-melnyk/flutter_advanced_switch#2]
How to implement a onchanged function for this switch ?

**Comment by alex-melnyk** [comment]
Use AdvancedSwitchController to manage or listen the switch state.

**Comment by trinhcanhphuc** [comment]
I want to save changed  value to my db, but I don't know how to use AdvancedSwitchController to save to db. Please help me. Thanks

**Comment by alex-melnyk** [comment]
@trinhcanhphuc @Yogesh-333  There is an example:

```dart
_controller01.addListener(() {
  final currentValue = _controller01.value;
});
```

**Comment by Osmosis311** [comment]
Do you really need a controller for every single switch? I'm showing switches for every item in a list view. How would I add controllers for all of those items?

**Comment by alex-melnyk** [comment]
> Do you really need a controller for every single switch? I'm showing switches for every item in a list view. How would I add controllers for all of those items?

@Osmosis311 makes sense, please check the next version:
Now you can use `initialValue` for setting value and `onChanged` to handle changes w/o the controller.

**Comment by Osmosis311** [comment]
Amazing! Thank you so much! This library is awesome.

**Comment by Osmosis311** [comment]
The new change works great! Thanks, again!
