### ISSUE TITLE
initial value is false after upgrading to 3.1.0

### ISSUE THREAD

**Issue by akalitenya** [alex-melnyk/flutter_advanced_switch#22]
flutter 13.19.4

The ValueNotifier initial value is shown as false, even if it is set to true

3.0.1 works

**Comment by alex-melnyk** [comment]
Looks like you have a mistake in the code, I double checked `initialValue` behaviour, it seems to me working good.
It will be more helpful if you have an example code to reproduce your case.

Other then that I did updated readme to show example with initialValue property set true.
