### ISSUE TITLE
Disabled state

### ISSUE THREAD

**Issue by vasilich6107** [alex-melnyk/flutter_advanced_switch#3]
Example has `disabled switch` section.
But they act like a regular ones.

**Comment by vasilich6107** [comment]
@alex-melnyk it seems it stopped working after changing state management approach

**Comment by alex-melnyk** [comment]
@vasilich6107 - version?

**Comment by vasilich6107** [comment]
latest

**Comment by vasilich6107** [comment]
I pulled from master to test an example

**Comment by vasilich6107** [comment]
@alex-melnyk I made a PR with fix
Could you check if it is ok?

**Comment by alex-melnyk** [comment]
Great work, thanks! Latest version published.

**Comment by vasilich6107** [comment]
Thanks for quick response!
Released wrapper for `reative_rorms` - https://pub.dev/packages/reactive_advanced_switch
