### ISSUE TITLE
Hover effect, courser to hand is missing

### ISSUE THREAD

**Issue by Wissperwind** [alex-melnyk/flutter_advanced_switch#8]
Hi,

Cool library! I use it for flutter web at the moment. But in web the users expect that the courser becoms a hand, if he hovers over the switch. Can you add this please?

**Comment by alex-melnyk** [comment]
> Hi,
> 
> 
> 
> Cool library! I use it for flutter web at the moment. But in web the users expect that the courser becoms a hand, if he hovers over the switch. Can you add this please?

Thanks, if you can fix that provide a PR please

**Comment by alex-melnyk** [comment]
Fixed
